<?php include APPLICATION_PATH.'/application/views/index/layout/_header.phtml'; ?>
    <div class="container" >
        <div id="tb" class="easyui-panel"   style="background-color:#f1f1f1">
            <div class="conditions" style="margin:20px 20px 20px ;">
                <span class="con-span">设备名称 </span>
                <input class="easyui-textbox" type="text" name="name" id="name" style="margin-left:10px;width:166px;height:35px;line-height:35px;">
                <span class="con-span">自定义码 </span>
                <input class="easyui-textbox" type="text" name="custom_code" id="custom_code" style="margin-left:10px;width:166px;height:35px;line-height:35px;">
                <span class="con-span">设备编码 </span>
                <input class="easyui-textbox" type="text" name="self_code" id="self_code" style="margin-left:10px;width:166px;height:35px;line-height:35px;">
                <a href="javascript:;" class="easyui-linkbutton query" style="margin-left:10px;" iconCls="icon-search" data-options="selected:true">查询</a>
                <a href="javascript:;" class="easyui-linkbutton reset" style="margin-left:10px;" iconCls="icon-reload">重置</a>
                <a href="/index.php?m=Machine&c=Machine&a=add" class="easyui-linkbutton" style="margin-left:10px;" data-options="selected:true">添加设备</a>
            </div>
        </div>
        <table id="dg" class="easyui-datagrid" ></table>
    </div>
    <div id="tuiguang" style="display:none"></div>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.list.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.grid.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/machine/list.js"></script>
<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>