<?php include APPLICATION_PATH.'/application/views/index/layout/_header_v2.phtml'; ?>
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>common/js/webuploader/0.1.5/webuploader.css">
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/webuploader/0.1.5/webuploader.js"></script> 
	<div style="margin:20px 0;"></div>
		<div style="padding:10px 60px 20px 60px">
	    <form id="ff" method="post" action="/index.php?m=Auth&c=Role&a=add&format=add">
	    	<table cellpadding="5" style="margin-bottom: 100px;">
	    		<tr>
	    			<td><span class="red">*</span> 名称</td>
	    			<td><input class="easyui-textbox"  type="text" name="info[name]"  style="width:300px;height:35px;line-height:35px;"></input></td>
	    		</tr>
	    		<tr>
	    			<td>描述</td>
	    			<td><input class="easyui-textbox" type="text" name="info[note]"  style="width:300px;height:35px;line-height:35px;"></input></td>
	    		</tr>
	    		<tr>
	    			<td>状态</td>
	    			<td>
	    				<input name="info[status]"  type="radio" id="status_radio-1" value="2" checked/>
						<label for="status_radio-1">正常</label>
						<input name="info[status]"  type="radio" style="margin-left:30px" id="status_radio-2" value="1" />
						<label for="status_radio-2">禁用</label>
					</td>
	    		</tr>
	    		</table>
	    		<div style="width:80%;hight:600px;border:1px solid #ccc;margin-bottom: 100px;">
    				<div style="background-color:#f5f5f5;border-bottom:1px solid #ccc;width:100%;height:30px;text-indent: 8px;line-height:30px;">
    					权限设置
    				</div>
	    			<div id="tab-system" class="formControls col-xs-8 col-sm-9 HuiTab form-ty-col">	
	    				<?php if ($parent) {?>
	    				<?php foreach ($parent as $key=>$value) {?>
    				    	<div class="tabCon" style="margin-left:10px">
        						<dl class="permission-list">
            						<dt>
                						<label>
                    						<input type="checkbox"    value="<?php echo $value['id']?>" name="per[<?php echo $value['id']?>]" class="per" id="per[<?php echo $value['id']?>]">
                    						<?php echo $value['name']?>
                						</label>
                						<?php if (!empty($value['childs'])) {?>
                							<span class="Hui-iconfont">&#xe67a;</span>
                						<?php }?>
            						</dt>
            						<?php if (!empty($value['childs'])) {?>
            						<?php foreach ($value['childs'] as $k=>$val) {?>
            							<dd>
                						<dl class="cl permission-list2" >
                    						<dt>
                        						<label class="list2">
                            						<input type="checkbox"   value="<?php echo $val['id']?>" name="per[<?php echo $val['id']?>]" class="per" id="per[<?php echo $val['id']?>]">
                            						<?php echo $val['name']?>
                        						</label>
                        						<?php if (!empty($val['childs'])) {?>
                        							<span class="Hui-iconfont">&#xe67a;</span>
                        						<?php }?>
                    						</dt>
                    						<dd style="margin-top:10px ">
                    							<?php if (!empty($val['childs'])) {?>
                    								<?php foreach ($val['childs'] as $kk=>$v) {?>
                                						<label style="margin-left:10px"  class="list2">
                                    						<input type="checkbox" value="<?php echo $v['id']?>" name="per[<?php echo $v['id']?>]" class="per" id="per[<?php echo $v['id']?>]">
                                    						<?php echo $v['name']?>
                                						</label>
                        						<?php }}?>
                    						</dd>
                						</dl>
                						</dd>
            						<?php }}?>
        						</dl>
    						</div>
						<?php }}?>
        			</div>	
	    		</div>
	    	
	    	<div style="padding:25px;position: fixed;bottom: 0px;width: 100%;background: #f1f1f1;text-align: center;margin-left: -70px;">
		    	<input type="submit" class="easyui-linkbutton" data-options="selected:true" value="保存" >
		    	<a href="/index.php?m=Auth&c=Role&a=list" style="margin-left:15px" class="easyui-linkbutton" >返回</a>
		    </div>
	    </form>
	    
	</div>

<script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/role/add.js"></script> 
<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>