<?php include APPLICATION_PATH.'/application/views/index/layout/_header_v2.phtml'; ?>
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>common/js/webuploader/0.1.5/webuploader.css">
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/webuploader/0.1.5/webuploader.js"></script>
    <style>
        table tr td:first-child {
            text-align: right;
        }
        table tr td:last-child {
            text-align: left;
        }
    </style>
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC; ?>common/css/table.css">
    <link href="<?php echo HOST_STATIC; ?>common/css/process.css" rel="stylesheet">

	<div style="margin:20px 0;"></div>
		<div style="padding:10px 60px 20px 60px">
	    <form  >
	    	<table class="table table-bordered" style="margin-bottom: 100px;">
	    		<tr>
	    			<td><span class="red">*</span> 账号</td>
	    			<td><?php echo $data['name']?></td>
	    		</tr>
	    		<tr>
	    			<td>姓名</td>
	    			<td><?php echo $data['fullname']?></td>
	    		</tr>
	    		<tr>
	    			<td>手机号</td>
	    			<td><?php echo $data['mobile']?></td>
	    		</tr> 
	    		<tr>
	    			<td>邮箱</td>
	    			<td><?php echo $data['email']?></td>
	    		</tr>
	    		<tr>
	    			<td><span class="red">*</span> 岗位</td>
	    			<td>
	    				<select disabled="disabled" style="width:300px;height:35px;line-height:35px;" name="info[role_id]">
	    					<?php if ($data['role_id'] > '0') {?>
    	    					<?php if ($parent) {?>
        	    					<?php foreach ($parent as $k=>$val) {?>
        	    						<option <?php if ($data['role_id'] == $val['id']) {?>selected="selected"<?php }?>value="<?php echo $val['id']?>"><?php echo $val['name']?></option>
        	    					<?php }?>
    	    					<?php }
                            } else {?>
                            	<option>超级管理员</option>
                            <?php }?>
	    				</select>
	    			</td>
	    		</tr>
	    		<tr>
	    			<td>状态</td>
	    			<td>
	    				<input name="info[status]"  type="radio" disabled="disabled" id="status_radio-1" value="2" <?php if ($data['status']=='2') {?>checked<?php }?>/>
						<label for="status_radio-1">正常</label>
						<input name="info[status]"  type="radio" disabled="disabled" style="margin-left:30px" id="status_radio-2" value="1" <?php if ($data['status']=='1') {?>checked<?php }?>/>
						<label for="status_radio-2">禁用</label>
					</td>
	    		</tr>
	    		</table>
	    		
	    	<div style="padding:25px;position: fixed;bottom: 0px;width: 100%;background: #f1f1f1;text-align: center;margin-left: -70px;">
		    	<a href="/index.php?m=Auth&c=Admin&a=list" style="margin-left:15px" class="easyui-linkbutton" >返回</a>
		    </div>
	    </form>
	    
	</div>
	    
<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>