<?php include APPLICATION_PATH.'/application/views/index/layout/_header.phtml'; ?>


<div class="row cl">
	<div style="text-align: center; padding: 10px 10px 5px 0;"
		class="no-print">
		<a href="javascript:;" onclick='moreprint(this);'
			class="easyui-linkbutton" data-options="selected:true">打印</a>
	</div>
</div>
<div id="barcode-print"
	style="text-align: center; width: 96%; margin: auto;">


	<div class="print-body"
		style="width: 60%; margin-left: 90px; padding: 5px 10px 5px 10px; border: 1px #ddd solid; position: relative;"
		data-id="<?php echo $detail['id'];?>" data-num="<?php echo $num;?>"
		data-self_code="<?php echo $detail['self_code'];?>" data-name="<?php echo $detail['name'];?>"
		data-sale_price="<?php echo $detail['sale_price'];?>"
		data-phone="<?php echo $detail['phone'];?>"
		data-company="<?php echo $detail['company'];?>"
		data-url="<?php echo $suppplier.'details?id='.$detail['id'];?>"
		>
		<div class="print-table">
			<table cellpadding="0" cellspacing="0" class="maintable" style="">
				<tbody>
					<tr>
						<td style="font-size: 15px; width: 60%;"><b><?php echo $detail['name'];?></b></td>
						<td rowspan="2" style="width: 40%;"><img width="100" height="100"
							src="/index.php?c=Public&a=qcode&content=<?php echo $suppplier;?>details?id=<?php echo $detail['id'];?> ">
						</td>
					</tr>
					<tr>
						<td style="font-size: 20px;"><b>¥<?php echo $detail['sale_price'];?></b></td>
					</tr>
					<tr>
						<td rowspan="2">
						<img width="100" height="50"
							style="margin-left: 5px;"						
							src="/index.php?c=Public&a=barcode&content=<?php echo$detail['self_code']?>"></td>
						<td   style="font-size: 12px;"><b id="phone" class="phone"  >电话<?php echo $detail['phone'];?></b></td>
					</tr>
					<tr>
						<td  style="font-size: 12px;"><b id="company" class="company" ><?php echo $detail['company'];?></b></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div style="border-top: 1px #ddd solid; padding-bottom: 6px; margin-top: 6px; background: #fff; padding-top: 6px; text-align: center;">
			打印数量<span style="font-size: 18px; color: #ff0000;"><?php echo $num;?></span>张
		</div>
	</div>
</div>

<script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/productnow/print.js"></script> 
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/calendar.js"></script> 
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/LodopFuncs.js"></script> 
<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>
