<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>支付页面</title>
    <link rel="stylesheet"
          href="<?php echo HOST_STATIC;?>mobile/css/style.css" />
    <link rel="stylesheet"
          href="<?php echo HOST_STATIC;?>mobile/css/weui.min.css" />

    <script type="text/javascript"
            src="<?php echo HOST_STATIC;?>common/custom/jquery.min.js"></script>

</head>
<body>

<!--头部  star-->
<header style="color:#fff">
    <a href="javascript:history.go(-1);">
        <div class="_left"><img src="<?php echo HOST_STATIC;?>mobile/images/left.png"></div><span>支付订单</span></a>
</header>
<!--头部 end-->

<!--内容 star-->
<div class="contaniner fixed-cont">
    <div class="pay_img"><img src="<?php echo HOST_STATIC;?>mobile/images/pay.jpg"></div>

    <div class="payTime">

        <div class="icon-box">
            <i class="weui-icon-success-circle weui-icon_msg"
               style="margin-left: 37%"></i>
            <div class="icon-box__ctn">
                <li><strong  style="font-size: 1.2rem;">保证金：¥<?php echo $info['margin'];?></strong></li>
                <li style="margin-top: .5rem;"><strong style="font-size: 1rem;">请确认金额，支付保证金</strong></li>
                <p class="icon-box__desc"
                   style="text-align: center; padding: 1rem;">注:若竞拍成功保证金小于成交价，将转为货款的一部分</p>
            </div>
        </div>

    </div>

    <!--支付 star-->
    <div class="pay">
        <div class="show">
            <?php
            if (strpos ( $_SERVER ['HTTP_USER_AGENT'], 'MicroMessenger' ) !== FALSE) {
                ?>
                <li>
                    <label>
                        <img src="<?php echo HOST_STATIC;?>mobile/images/weixin.png" >微信支付
                        <input name="payRadio"type="radio" value="1" checked/>
                        <span></span>
                    </label>
                </li>
                <?php
            } else {
                ?>
                <li>
                    <label>
                        <img src="<?php echo HOST_STATIC; ?>mobile/images/zhifubao.png">支付宝支付
                        <input name="payRadio" type="radio" value="2" checked/>
                        <span></span>
                    </label>
                </li>
                <?php
            }
            ?>
          
          
         	
                    <div style="border-bottom-color:">
                       <input style="margin-left: 15px;margin-top: 30px;" if="accept" type="checkBox" />我同意
                        <a href="https://<?php echo $_SERVER ['HTTP_HOST']?>/v1/Payment/copywriting?identif=<?=$_GET['identif']?>"   style="color:#0000CD;">"竞拍协议"</a>
                        <p style="font-size:8px;margin-top: -10px;padding: 10px;">提示：一旦竞拍成功，保证金作为成交价的一部分，实际支付时将扣除保证金额</p>
                    </div>
                
          
        </div>
       

    </div>
    <!--支付 end-->
 
</div>


<div class="book-recovery-bot2" id="footer">
    <a href="#" onclick="onBridgeReady()"><div class="payBottom">
            <li class="textfr">确认支付:</li>
            <li class="textfl"><span>¥<?php echo $info['margin'];?></span></li>
        </div>
    </a>
</div>
<!--内容 end-->

<script type="text/javascript"
        src="https://res.wx.qq.com/open/js/jweixin-1.3.0.js"></script>
<script type="text/javascript">

    function onBridgeReady()
    {
		 var accept = $("input[type='checkbox']").is(':checked');
			
		if(accept == false){
			alert("请认真阅读竞拍协议！");
			return;
		}
		
		
		$("#book-recovery-bot2").attr('disabled','true');
         
	
        var noteData = new Object();
        noteData['info[seckill_id]'] = <?php echo $info['id'];?>;
        noteData['info[margin]'] = <?php echo $info['margin'];?>;
        noteData['info[user_id]'] = <?php echo $info['user_id'];?>;
        noteData['info[address_id]'] = <?php echo $info['address_id'];?>;
        noteData['info[product_id]'] = <?php echo $info['product_id'];?>;
        noteData['info[delivery_type]'] = <?php echo $info['delivery_type'];?>;

        $.ajax({
            type:"POST",
            async:true,
            url:'/v1/Order/createMargin?identif=<?=$_GET['identif']?>&format=add',
            data:noteData,
            dataType: "json",
            success:function(data){

                if(data.code == 200){
                	$("#book-recovery-bot2").removeAttr('disabled');
                    if (window.__wxjs_environment == 'miniprogram') {//小程序支付
                        var API_URL = encodeURIComponent('<?= HOST_API;?>');
                        wx.miniProgram.redirectTo({url:'/pages/pay?orderId='+data.id+'&payCompanyId=1&apiUrl='+API_URL+'&identif=<?=$_GET['identif']?>&biz_type=margin'})
                    } else {

                        var val_payPlatform = $('input[name="payRadio"]:checked').val();
                        $.ajax({
                            type: "POST",
                            async:true,  // 设置同步方式
                            url: '/v1/payment/createmargin',
                            data: {
                                orderId:data.id,
                                payCompanyId:val_payPlatform,
                                identif:'<?=$_GET['identif']?>',
                                openId:'<?=$wxinfo['openid']?>',
                                callback:'<?=urlencode($callback);?>'
                            },
                            dataType: "json",
                            success:function(res){
                                if (res.errno != '0') {
                                    alert(res.errmsg);
                                    return;
                                }
                                if (val_payPlatform == 1) {
                                    WeixinJSBridge.invoke(
                                        'getBrandWCPayRequest',  {
                                            "appId":res.result.appId,     //公众号名称，由商户传入
                                            "timeStamp":res.result.timeStamp+"",         //时间戳，自1970年以来的秒数
                                            "nonceStr":res.result.nonceStr, //随机串
                                            "package":res.result.package,
                                            "signType":res.result.signType,         //微信签名方式：
                                            "paySign":res.result.paySign //微信签名
                                        },
                                        function(res){
                                            if(res.err_msg == "get_brand_wcpay_request:ok" ) {
                                                location.href="<?php echo urldecode($callback);?>";
                                            } else {
                                                //微信支付失败后处理
                                                $.ajax({
                                                    type: "POST",
                                                    async:true,  // 设置同步方式
                                                    url: '/v1/bidding/payfailure?identif=<?=$_GET['identif']?>',
                                                    data: {
                                                        orderId:data.id
                                                    },
                                                    dataType: "json",
                                                    success:function(res){

                                                    }

                                                });


                                            }
                                        }
                                    );
                                } else if(val_payPlatform == 2) {
                                    $('body').html(res.result.from)
                                }

                            }
                        });
                    }
                }
            }
        });



    }



</script>

</body>
</html>




