<!DOCTYPE html>
<html>

<head>
<meta charset="utf-8">
<meta name="viewport"
	content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>支付页面</title>
<link rel="stylesheet"
	href="<?php echo HOST_STATIC;?>mobile/css/style.css" />


<script type="text/javascript"
	src="<?php echo HOST_STATIC;?>common/custom/jquery.min.js"></script>

</head>
<body>

	<!--头部  star-->
	<header style="color: #fff">
		<a href="javascript:history.go(-1);">
			<div class="_left">
				<img src="<?php echo HOST_STATIC;?>mobile/images/left.png">
			</div> <span>支付订单</span>
		</a>
	</header>
	<!--头部 end-->

	<!--内容 star-->
	<div class="contaniner fixed-cont">
		<div class="pay_img">
			<img src="<?php echo HOST_STATIC;?>mobile/images/pay.jpg">
		</div>

		<div class="payTime">
			<li><strong>¥<?php echo $orderInfo['order_actual_amount'];?></strong></li>
			<li>订单号:<?php echo $orderInfo['order_no'];?></li>
			<li>剩余时间<span id="timer" style="color: red"><?=$time['time_i']?>分<?=$time['time_s']?>秒</span></li>
		</div>

		<!--支付 star-->
		<div class="pay">
			<div class="show">
                <?php
																if (strpos ( $_SERVER ['HTTP_USER_AGENT'], 'MicroMessenger' ) !== FALSE) {
																	?>
                <li><label> <img
						src="<?php echo HOST_STATIC;?>mobile/images/weixin.png">微信支付 <input
						name="payRadio" type="radio" value="1" checked /> <span></span>
				</label></li>
                <?php
																} else {
																	?>
                <li><label> <img
						src="<?php echo HOST_STATIC; ?>mobile/images/zhifubao.png">支付宝支付 <input
						name="payRadio" type="radio" value="2" checked /> <span></span>
				</label></li>
                <?php
																}
																?>
                <!--                  <li><label><img src="<?php echo HOST_STATIC;?>mobile/images/yue.png" >余额支付<input name="Fruit" type="radio" value="" /><span></span></label> </li>
              <li class="center"><a href="#" onClick="showHideCode()">查看更多支付方式↓</a></li>-->
			</div>
			<!--            <div class="showList" id = "showdiv" style="display:none;">-->
			<!--                <li><label><img src="-->
			<?php //echo HOST_STATIC;?>
			<!--mobile/images/yinhang.png" >银行卡<input name="Fruit" type="radio" value="" /><span></span></label> </li>-->
			<!--                <li><label><img src="-->
			<?php //echo HOST_STATIC;?>
			<!--mobile/images/weixin.png" >添加更多<input name="Fruit" type="radio" value=""/><span></span></label> </li>-->
			<!---->
			<!--                <li style="background:none" ></li>-->
			<!--            </div>-->
		</div>
		<!--支付 end-->


	</div>


	<div class="book-recovery-bot2" id="footer">
		<a href="#" onclick="onBridgeReady()"><div class="payBottom">
				<li class="textfr">确认支付:</li>
				<li class="textfl"><span>¥<?php echo $orderInfo['order_actual_amount'];?></span></li>
			</div> </a>
	</div>
	<!--内容 end-->

	<script type="text/javascript"
		src="https://res.wx.qq.com/open/js/jweixin-1.3.0.js"></script>
	<script type="text/javascript">

        function onBridgeReady()
        {
            
            if (window.__wxjs_environment == 'miniprogram') {//小程序支付
                var API_URL = encodeURIComponent('<?= HOST_API;?>');
                wx.miniProgram.redirectTo({url:'/pages/pay?orderId=<?=$orderInfo['id'];?>&payCompanyId=1&apiUrl='+API_URL+'&identif=<?=$_GET['identif']?>'})
            } else {

                var val_payPlatform = $('input[name="payRadio"]:checked').val();
                $.ajax({
                    type: "POST",
                    async:true,  // 设置同步方式
                    url: '/v1/payment/create',
                    data: {
                        orderId:'<?=$orderInfo['id'];?>',
                        payCompanyId:val_payPlatform,
                        identif:'<?=$_GET['identif']?>',
                        openId:'<?=$wxinfo['openid']?>',
                        callback:'<?=urlencode($callback);?>'
                    },
                    dataType: "json",
                    success:function(res){
                        
                        if (res.errno != '0') {
                            alert(res.errmsg);
                            return;
                        }
                        if (val_payPlatform == 1) {
                            WeixinJSBridge.invoke(
                                'getBrandWCPayRequest',  {
                                    "appId":res.result.appId,     //公众号名称，由商户传入
                                    "timeStamp":res.result.timeStamp+"",         //时间戳，自1970年以来的秒数
                                    "nonceStr":res.result.nonceStr, //随机串
                                    "package":res.result.package,
                                    "signType":res.result.signType,         //微信签名方式：
                                    "paySign":res.result.paySign //微信签名
                                },
                                function(res){
                                    if(res.err_msg == "get_brand_wcpay_request:ok" ) {
                                        location.href="<?php echo urldecode($callback);?>";
                                    }     // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回    ok，但并不保证它绝对可靠。
                                }
                            );
                        } else if(val_payPlatform == 2) {
                            $('body').html(res.result.from)
                        }

			if(res.result.single == '200'){
				 {
                     location.href=res.result.callback;
                   
                   }}
                        
                    }
                });
            }
        }

        // if (typeof WeixinJSBridge == "undefined"){
        // if( document.addEventListener ){
        // document.addEventListener('WeixinJSBridgeReady', onBridgeReady, false);
        // }else if (document.attachEvent){
        // document.attachEvent('WeixinJSBridgeReady', onBridgeReady);
        // document.attachEvent('onWeixinJSBridgeReady', onBridgeReady);
        // }
        // }else{
        // }


        var maxtime = <?=$time['time_m']?>; //40分钟，按秒计算，自己调整!
        function CountDown() {
            if (maxtime >= 0) {
                minutes = Math.floor(maxtime / 60);
                if (minutes<10) minutes = '0'+minutes;
                seconds = Math.floor(maxtime % 60);
                if (seconds<10) seconds = '0'+seconds;
                msg = "" + minutes + "分" + seconds + "秒";
                document.all["timer"].innerHTML = msg;
                --maxtime;
            } else{
                clearInterval(timer);
            }
        }
        timer = setInterval("CountDown()", 1000);

        function showHideCode(){
            $("#showdiv").toggle();
        }
    </script>

</body>
</html>




