<?php include APPLICATION_PATH.'/application/views/index/layout/_header.phtml'; ?>
	<div class="container" >

	 <div id="tb" class="easyui-panel"   style="background-color:#f1f1f1">
      <table id="dg"   class="easyui-datagrid" ></table>
 </div>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.list.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.grid.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/machineservicelog/list.js"></script>

<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>