<?php include APPLICATION_PATH.'/application/views/index/layout/_header.phtml'; ?>
    <link href="<?php echo HOST_STATIC;?>common/css/login/login.css" rel="stylesheet">
	<div class="login-hd">
		<div class="left-bg"></div>
		<div class="right-bg"></div>
		<div class="hd-inner">
			<span class="logo"></span>
			<span class="split"></span>
			<span class="sys-name">商户管理系统</span>
		</div>
	</div>
	<div class="login-bd">
		<div class="bd-inner">
			<div class="inner-wrap">
				<div class="lg-zone">
					<div class="lg-box">
						<div class="lg-label"><h4>没有访问权限</h4></div>
					</div>					
				</div>
				<div class="lg-poster"></div>
			</div>
		</div>
	</div>
	<div class="login-ft">
		<div class="ft-inner">
			<div class="about-us">
				<a href="javascript:;">关于我们</a>
				<a href="javascript:;">法律声明</a>
				<a href="javascript:;">服务条款</a>
				<a href="javascript:;">联系方式</a>
			</div>
			<div class="address">地址：北京市海淀区马连洼北路8号C座五层506-A031&nbsp;邮：100001&nbsp;&nbsp;Copyright&nbsp;©&nbsp;2019&nbsp;-&nbsp;2019&nbsp;北京扎呵呵科技有限公司&nbsp;版权所有</div>
			<div class="other-info">建议使用IE8及以上版本浏览器&nbsp;京ICP备18022684号-1&nbsp;E-mail：posteradmin@zhahehe.com</div>
		</div>
	</div>
<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>