<?php include APPLICATION_PATH . '/application/views/index/layout/_header_v2.phtml'; ?>
    <link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC; ?>common/css/table.css">
    <link href="<?php echo HOST_STATIC; ?>common/css/process.css" rel="stylesheet">

    <div style="margin:20px 0;"></div>
    <div style="padding:10px 60px 20px 60px">

        <table class="table table-bordered" style="margin-bottom: 100px;">
            <tbody>
            <tr>
                <th style="min-width: 100px;width: 100px">采购名称</th>
                <td><?php echo $assigns['purchase']['title'] ?></td>
            </tr>
            <tr>
                <th>姓名</th>
                <td><?php echo $assigns['purchase']['name'] ?></td>
            </tr>
            <tr>
                <th>手机号</th>
                <td><?php echo $assigns['purchase']['mobile'] ?></td>

            </tr>

            <tr>
                <th>收货地址</th>
                <td><?php echo $assigns['purchase']['district_text'] ?></td>
            </tr>
            <tr>
                <th>详细地址</th>
                <td><?php echo $assigns['purchase']['address'] ?></td>
            </tr>

            <tr>
                <th>支付方式</th>
                <td>

                    <p><?php echo $assigns['purchase']['pay_type_text'] ?></p>
                    <div>打款账户：<?php echo BANK_ACCOUNT; ?></div>
                    <div>银行名称：<?php echo BANK_BRANCH_NAME; ?></div>
                    <div>账号名称：<?php echo BANK_ACCOUNT_NAME; ?></div>

                </td>
            </tr>

            <tr>
                <th>状态</th>
                <td><?php echo $assigns['purchase']['order_status_text'] ?></td>
            </tr>
            <!--选择商品 start -->
            <tr>
                <th>选择商品</th>
                <td>

                    <?php foreach ((array)$assigns['purchase']['child_order'] as $key => $order) { ?>
                        <div>
                            <div style="margin: 15px 0">
                                子订单号：<?php echo $order['child_order_no']; ?>
                                <span style="margin-left: 20px;">
                                    下单时间：<?php echo $order['created_at']; ?>
                                </span>
                                <span style="margin-left: 20px;">
                                    订单状态：<?php echo $order['order_status_text']; ?>
                                </span>
                                <span style="margin-left: 20px;">
                                    <input class="easyui-linkbutton show-express"
                                           data-options="selected:true"
                                           value="查看物流"
                                           data-child-order-no="<?php echo $order['child_order_no']; ?>" type="button">
                                </span>
                            </div>
                            <div style="overflow: auto; width: 800px;">
                                <table class="table table-bordered" style="text-align: center">
                                    <tr class="info">
                                        <th style="min-width: 80px">序号</th>
                                        <th style="min-width: 100px">商品图片</th>
                                        <th style="min-width: 150px">商品编号</th>
                                        <th style="min-width: 200px">商品名称</th>
                                        <th style="min-width: 150px">分类</th>
                                        <th style="min-width: 150px">品牌</th>
                                        <th style="min-width: 120px">市场价</th>
                                        <th style="min-width: 120px">供应价</th>
                                        <th style="min-width: 80px">数量</th>
                                        <th style="min-width: 80px">小计</th>
                                    </tr>
                                    <?php foreach ((array)$order['products'] as $k => $product) { ?>
                                        <tr>
                                            <td><?php echo $k + 1; ?></td>
                                            <td>
                                                <div class="imgbox">
                                                    <img class="smallimg" src="<?php echo $product['img_url']; ?>" alt=""></div>
                                            </td>
                                            <td><?php echo $product['self_code']; ?></td>
                                            <td
                                                    title="<?php echo $product['product_name']; ?>"><?php echo mb_strimwidth($product['product_name'], 0, 40, '...'); ?></td>
                                            <td><?php echo $product['category_name']; ?></td>
                                            <td><?php echo $product['brand_name']; ?></td>
                                            <td><?php echo $product['market_price']; ?></td>
                                            <td><?php echo $product['channel_price']; ?></td>
                                            <td><?php echo $product['num']; ?></td>
                                            <td><?php echo $product['price']; ?></td>
                                        </tr>
                                    <?php } ?>
                                    <tr>
                                        <td>总计</td>
                                        <td colspan="8"></td>
                                        <td><?php echo $order['child_order_original_amount'] ?></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    <?php } ?>
                </td>
            </tr>
            <!-- 选择商品 end -->


            <tr>
                <th>购买总数</th>
                <td><?php echo $assigns['purchase']['amount'] ?></td>
            </tr>
            <tr>
                <th>购买总额</th>
                <td><?php echo $assigns['purchase']['price'] ?></td>
            </tr>

            <?php
            if ($assigns['purchase']['remittance_account']) {
                ?>
                <tr>
                    <th>汇款编号</th>
                    <td>
                        <?php echo $assigns['purchase']['remittance_account'] ?>
                    </td>
                </tr>
                <?php
            }
            ?>
            <?php
            if ($assigns['purchase']['remittance_images']) {
                ?>
                <tr>
                    <th>汇款图片</th>

                    <td>
                        <?php foreach ((array)$assigns['purchase']['remittance_images'] as $image) { ?>
                            <div class="imgbox">
                                <img src="<?php echo $image ?>" class="smallimg">
                            </div>
                        <?php } ?>
                    </td>
                </tr>
                <?php
            }
            ?>
            <tr>
                <th></th>
                <td>
                </td>
            </tr>
            </tbody>
        </table>
        <div style="padding:25px;position: fixed;bottom: 0px;width: 100%;background: #f1f1f1;text-align: center;margin-left: -70px;">
                    <?php
                    if ($assigns['type'] == '1') {
                        ?>
                        <?php if ($_GET['origin'] == 'recovery') { ?>
                            <a href="/index.php?m=Recovery&c=Recovery&a=list" style="margin-left:15px" class="easyui-linkbutton" >返回</a>
                        <?php } else { ?>
                            <a href="/index.php?m=Purchase&c=Purchase&a=list" style="margin-left:15px" class="easyui-linkbutton">返回</a>
                        <?php }?>
                        <?php
                    } else if ($assigns['type'] == '2') {
                        ?>
                        <a href="/index.php?m=Order&c=Order&a=list" style="margin-left:15px" class="easyui-linkbutton">返回</a>
                        <?php
                    }?>
          </div>          
                    
    </div>

<?php include APPLICATION_PATH . '/application/views/index/templates/common/express_box_dialog.phtml'; ?>
<?php include APPLICATION_PATH . '/application/views/index/templates/common/img_box.phtml'; ?>

    <script type="text/javascript">

        $(function () {
            $("body").on('click', '.show-express', function () {
                var formData = {};
                formData.child_order_no = $(this).data('child-order-no');
                formData.format = 'query_express';
                $.post('index.php?m=Purchase&c=Purchase&a=detail&id=<?php echo $assigns['purchase']['id'] ?>', formData, function (response) {
                    if (response.code === 500) {
                        $.messager.alert('提示', response.msg);
                        return false;
                    }
                    $("#express-box-dialog").html(template('express-box-tpl', {express: response.data}));
                    $("#express-box-dialog").window('open');
                }, 'json');
            });
        });

    </script>

<?php include APPLICATION_PATH . '/application/views/index/layout/_footer.phtml'; ?>