<?php include APPLICATION_PATH . '/application/views/index/layout/_header.phtml'; ?>
    <div class="container">


        <!--搜索 start-->
        <form id="ff">
            <div id="tb" class="easyui-panel" style="background-color:#f1f1f1">
                <div class="conditions" style="margin:20px 20px 20px ;">
                    <span class="con-span">采购单号 </span>
                    <input class="easyui-textbox " type="text" name="info[code]" id="code"
                           style="margin-left:10px;width:166px;height:35px;line-height:35px;">

                    <span class="con-span">采购名称</span>
                    <input class="easyui-textbox " type="text" name="info[title]" id="title"
                           style="margin-left:10px;width:166px;height:35px;line-height:35px;">

                    <a href="javascript:;" class="easyui-linkbutton query" style="margin-left:10px;"
                       iconCls="icon-search" data-options="selected:true">查询</a>

                    <a href="javascript:;" class="easyui-linkbutton reset"
                       style="margin-left:10px;"
                       iconCls="icon-reload">重置</a>

                    <a href="javascript:;" class="easyui-linkbutton more" style="margin-left:10px;"
                       iconCls="icon-more">更多</a>


                </div>
                <div class="conditions hide" style="margin:20px 20px 20px ">


                    <span class="con-span">姓名 </span>
                    <input class="easyui-textbox " type="text" name="info[name]" id="name"
                           style="margin-left:10px;width:166px;height:35px;line-height:35px;">
                    <span class="con-span">用户手机 </span>
                    <input class="easyui-textbox " type="text" name="info[mobile]" id="mobile"
                           style="margin-left:10px;width:166px;height:35px;line-height:35px;">

                    <span class="con-span">订单状态 </span>
                    <select class="easyui-combobox" name="info[order_status]" id="order_status"
                            style="margin-right:10px;width:166px;height:35px;line-height:35px;">
                        <option value="">-请选择订单状态-</option>
                        <?php
                        foreach ($data['order_status'] as $key => $type) {
                            echo "<option value='{$key}'>{$type['name']}</option>";
                        }
                        ?>
                    </select>

                    <span class="con-span">快递单号 </span>
                    <input class="easyui-textbox " type="text" name="info[express_no]" id="express_no"
                           style="margin-left:10px;width:166px;height:35px;line-height:35px;">

                </div>

                <div class="conditions hide" style="margin:20px 20px 20px ">

                    <span class="con-span">付款方式 </span>
                    <select class="easyui-combobox" name="info[pay_type]" id="pay_type"
                            style="margin-right:10px;width:166px;height:35px;line-height:35px;">
                        <option value="">-请选择付款方式-</option>
                        <?php
                        foreach ($data['pay_types'] as $key => $type) {
                            echo "<option value='{$key}'>{$type}</option>";
                        }
                        ?>
                    </select>

                    <span class="con-span">省 </span>
                    <select class="easyui-combobox" name="info[province_id]" id="province_id"
                            style="margin-right:10px;width:166px;height:35px;line-height:35px;"></select>

                    <span class="con-span">市 </span>
                    <select class="easyui-combobox" name="info[city_id]" id="city_id"
                            style="margin-right:10px;width:166px;height:35px;line-height:35px;"></select>

                    <span class="con-span">区 </span>
                    <select class="easyui-combobox" name="info[area_id]" id="area_id"
                            style="width:166px;height:35px;line-height:35px;"></select>

                </div>

                <div class="conditions hide" style="margin:20px 20px 20px ">

                    <span class="con-span">发货时间 </span>
                    <input class="easyui-datebox " style="width:166px;height:35px;line-height:35px;"
                           name="info[deliver_start_time]" id="deliver_start_time"/>
                    <span class="con-span"> —— </span>
                    <input class="easyui-datebox " style="width:166px;height:35px;line-height:35px;"
                           name="info[deliver_end_time]" id="deliver_end_time"/>

                    <span class="con-span">下单时间 </span>
                    <input class="easyui-datebox " style="width:166px;height:35px;line-height:35px;"
                           name="info[order_start_time]" id="order_start_time"/>
                    <span class="con-span"> —— </span>
                    <input class="easyui-datebox " style="width:166px;height:35px;line-height:35px;"
                           name="info[order_end_time]" id="order_end_time"/>

                </div>
                <div class="opt-buttons" style="margin:20px 20px 20px ">
                    <a href="/index.php?m=Purchase&c=Purchase&a=add" class="easyui-linkbutton"
                       data-options="selected:true">新增</a>
                </div>
            </div>
        </form>
        <!--   搜索 end     -->
        <!--   数据 start     -->
        <table id="dg" class="easyui-datagrid"></table>
        <!--   数据 start     -->

    </div>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.list.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.grid.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/area.js"></script>
    <script type="text/javascript">
        var purchase_order = JSON.parse('<?php echo $data['purchase_status']?>');
        var fields = [[{
            field: 'id',
            width: 100,
            sortable: true,
            title: 'ID'
        }, {
            field: 'purchase_title',
            width: 200,
            title: '采购名称'
        }, {
            field: 'order_no',
            width: 150,
            title: '采购单号'
        }, {
            field: 'child_order_no',
            width: 150,
            title: '子订单号'
        }, {
            field: 'child_order_status_text',
            width: 100,
            title: '订单状态'
        }, {
            field: 'pay_type_text',
            width: 100,
            title: '付款方式'
        }, {
            field: 'purchase_name',
            width: 100,
            title: '姓名'
        }, {
            field: 'purchase_mobile',
            width: 100,
            title: '手机'
        }, {
            field: 'delivery_time',
            width: 150,
            title: '发货时间'
        }, {
            field: 'purchase_created_at',
            width: 150,
            title: '下单时间'
        }, {
            field: 'operate_purchase',
            title: '操作',
            align: 'center',
            formatter: function (value, row, index) {
                return showOperatorPurchase(value, row, index);
            }
        }, {
            field: 'operate_order',
            title: '操作',
            align: 'center',
            formatter: function (value, row, index) {
                return showOperatorOrder(value, row, index);
            }
        }]
        ];

        /**
         * 显示操作项
         * @param value 字段的值。
         * @param row 行的记录数据。
         * @param index 行的索引。
         * @returns {string}
         */
        function showOperatorPurchase(value, row, index) {
            var main_status = parseInt(row.main_status);
            var operator = [];
            operator.push({'action': 'detail', 'name': '查看'});
            switch (main_status) {
                case purchase_order.status_10:
                    operator.push({'action': 'audit', 'name': '审核'});
                    operator.push({'action': 'cancel', 'name': '取消'});
                    break;
                case purchase_order.status_20:
                    operator.push({'action': 'pay', 'name': '付款'});
                    operator.push({'action': 'cancel', 'name': '取消'});
                    break;
                case purchase_order.status_80:
                    operator.push({'action': 'delete', 'name': '删除'});
                    break;
            }


            return QDDGrid.renderOperator(operator, row, index);
        }

        /**
         * 显示操作项
         * @param value 字段的值。
         * @param row 行的记录数据。
         * @param index 行的索引。
         * @returns {string}
         */
        function showOperatorOrder(value, row, index) {
            var child_status = parseInt(row.child_status);
            var operator = [];
            switch (child_status) {
                case purchase_order.status_10:
                    break;
                case purchase_order.status_20:
                    break;
                case purchase_order.status_21:
                    break;
                case purchase_order.status_30:
                    break;
                case purchase_order.status_40:
                    break;
                case purchase_order.status_50:
                    operator.push({'action': 'receipt', 'name': '确认收货'});
                    //判断是否需要退款
                    if (row.is_return == 1) {
                        // operator.push({'action': 'salesreturn', 'name': '退货'});
                    }
                    break;
                case purchase_order.status_60:
                    if (row.is_return == 2 && !row.has_return_order && row.is_can_return === 1) {
                        operator.push({'action': 'salesreturn', 'name': '退货'});
                    }
                    break;
                case purchase_order.status_80:
                    // operator.push({'action': 'delete', 'name': '删除'});
                    break;
                case purchase_order.status_90:
                    // /operator.push({'action': 'delete', 'name': '删除'});
                    break;
            }
            return QDDGrid.renderOperator(operator, row, index);
        }

        /**
         * 此处扩展默认的网格属性
         * @type {{action: function | string}}
         */
        var options = {
            onLoadSuccess: function (data) {
                var cell = {};
                var row = data.rows;
                for (var i = 0; i < row.length; i++) {
                    if (typeof cell[row[i].order_no] === "undefined") {
                        cell[row[i].order_no] = {
                            rowspan: 1,
                            index: i
                        };
                    } else {
                        cell[row[i].order_no].rowspan++;
                    }
                }

                for (var j in cell) {
                    if (typeof cell[j] !== 'undefined') {
                        //合并采购编号
                        $('#dg').datagrid('mergeCells', {
                            index: cell[j].index,
                            field: 'order_no',
                            rowspan: cell[j].rowspan,
                        });
                        //合并采购名称
                        $('#dg').datagrid('mergeCells', {
                            index: cell[j].index,
                            field: 'purchase_title',
                            rowspan: cell[j].rowspan,
                        });
                        //合并采购操作
                        $('#dg').datagrid('mergeCells', {
                            index: cell[j].index,
                            field: 'operate_purchase',
                            rowspan: cell[j].rowspan,
                        });
                    }
                }
                //更新缓存page
                var options = $('#dg').datagrid("getPager").data("pagination").options;
                QDDGrid.setPageData(options.pageNumber, options.pageSize, location.href + '&format=list');

            }
        };

        /**
         * 此处扩展默认的处理动作
         * @type {{action: function | string}}
         */
        var handles = {
            // 这里是主订单操作
            detail: function (row) {
                QDDGrid.redirect("?m=Purchase&c=Purchase&a=detail&id=" + row.purchase_id);
            },
            audit: function (row) {
                handleConfirm("?m=Purchase&c=Purchase&a=audit&id=" + row.purchase_id, '审核');
            },
            cancel: function (row) {
                handleConfirm("?m=Purchase&c=Purchase&a=cancel&id=" + row.purchase_id, '取消');
            },
            pay: function (row) {
                QDDGrid.redirect("?m=Purchase&c=Purchase&a=pay&id=" + row.purchase_id);
            },
            delete: function (row) {
                handleConfirm("?m=Purchase&c=Purchase&a=delete&id=" + row.purchase_id, '删除');
            },
            // 这里是子订单操作
            salesreturn: function (row) {
                QDDGrid.redirect("?m=Purchase&c=Purchase&a=return&order=" + row.child_order_no);
            },

            receipt: function (row) {
                handleConfirm("?m=Purchase&c=Purchase&a=receipt&purchase_id=" + row.purchase_id + "&child_order_no=" + row.child_order_no, '确认收货');
            }
        };

        $(function () {
            area_child(0, 1);
        });

    </script>


<?php include APPLICATION_PATH . '/application/views/index/layout/_footer.phtml'; ?>