<html lang="en"> 
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>扎呵呵后台管理系统</title>
<link href="<?php echo HOST_STATIC;?>common/css/base.css" rel="stylesheet">
<link href="<?php echo HOST_STATIC;?>common/css/providers1.css" rel="stylesheet">
<link rel="stylesheet" href="<?php echo HOST_STATIC;?>common/custom/ui-admin/easyui.css">
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>common/custom/ui-admin/icon.css">
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>common/custom/ui-admin/iconfont.css">
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/custom/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/custom/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/custom/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/custom/datagrid-detailview.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/json2.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/template-web.js"></script>
<!--[if lt IE 9]>
    <script src="<?php echo HOST_STATIC;?>common/js/common/html5shiv.js"></script>
<![endif]-->	
<script src="<?php echo HOST_STATIC;?>common/js/common/jquery.lazyload.js?v=1.9.1"></script>
<script type="text/javascript">
	var HOST_FILE = '<?php echo HOST_FILE;?>';
	var HOST_STATIC = '<?php echo HOST_STATIC;?>';
</script>
<style type="text/css">
.container .easyui-panel
{
	margin-left: 0px !important; 
	margin-right: 0px !important; 
	width: 100% !important;
}
.container .panel-title
{
	margin-left: 0px !important; 
	margin-right: 0px !important; 
	width: 100% !important;
}
.container .panel{
	margin-left: 0px !important; 
	margin-right: 0px !important; 
	width: 100% !important;
}
</style>
</head> 
<body class="white">
<?php echo $menu_html;?>
