<?php
header ( 'Content-type:text/html;charset=utf-8' );
include_once APPLICATION_PATH . "/application/library/Pay/Hfb/Hfb/func/HFBConfig.php";
?>

<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--[if lt IE 10]>
<script>alert("为了更好的体验，不支持IE10以下的浏览器。请选择google chrome 或者 firefox 浏览器。"); location.href="http://www.hefupal.com";</script>
<![endif]-->
<link rel="stylesheet"
	href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet"
	href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<title>易势支付-商户demo</title>
<style type="text/css">
body {
	padding-top: 70px;
}
</style>

</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<a class="navbar-brand" href="index.html"><strong>首页</strong></a> <a
				class="navbar-brand"><strong>支付（<s>ie1-9</s>）
			</strong></a>
		</div>
	</nav>

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<form role="form" action="/v1/hfb/scanpayhandler/?identif=test"
					method="post" name="payForm">
					<div class="form-group">
						<label for="amount">交易金额</label> <input type="text"
							class="form-control" name="amount" id="amount"
							value="<?=$money;?>" required /> <input type="text"
							class="form-control" name="orderId" id="orderId"
							value="<?=$orderId;?>" hidden />
					</div>
					<div class="form-group">
						<label for=payType>支付方式</label> <select class="form-control"
							name="payType">
							<option value="1">微信扫码支付</option>
							<option value="2">支付宝扫码支付</option>
							<option value="3">微信公众号支付</option>
							<option value="4">支付宝服务窗支付</option>
							<option value="7">QQ钱包支付</option>
							<option value="8">微信WAP支付</option>
							<option value="9">支付宝WAP支付</option>
							<option value="10">微信APP支付</option>
						</select>
					</div>
					<div class="form-group">
						<label for="notifyUrl">结果通知地址</label> <input type="text"
							class="form-control" name="notifyUrl"
							value="<?php echo NOTIFY_URL ?>" id="notifyUrl" required />
					</div>
					<div class="form-group">
						<label for="bindId">入驻ID</label> <input type="text"
							class="form-control" name="bindId" id="bindId"
							value="<?php echo bindId ?>" required />
					</div>
					<div class="form-group">
						<label for="remark">付款摘要</label> <input type="text"
							class="form-control" name="remark" value="摘要" id="remark"
							required />
					</div>

					<div class="form-group">
						<label for="bizType">业务代码</label> <input type="text"
							class="form-control" value="01" name="bizType" id="bizType"
							required />
					</div>
					<div class="form-group">
						<label for="goodsName">商品名称</label> <input type="text"
							class="form-control" value="测试商品名称" name="goodsName"
							id="goodsName" required />
					</div>
					<div class="form-group">
						<label for="goodsInfo">商品信息</label> <input type="text"
							class="form-control" name="goodsInfo" id="goodsInfo" />
					</div>
					<div class="form-group">
						<label for="goodsNum">商品数量</label> <input type="text"
							class="form-control" name="goodsNum" id="goodsNum" />
					</div>
					<div class="form-group">
						<label for="buyerName">买家姓名</label> <input type="text"
							class="form-control" name="buyerName" id="buyerName" value="张三"
							required />
					</div>
					<div class="form-group">
						<label for="contact">买家联系方式</label> <input type="text"
							class="form-control" name="contact" id="contact" />
					</div>
					<div class="form-group">
						<label for="buyerId">买家ID</label> <input type="text"
							class="form-control" name="buyerId" value="1234567" id="buyerId"
							required />
					</div>

					<div class="form-group">
						<label for="ext1">扩展字段1</label> <input type="text"
							class="form-control" name="ext1" id="ext1">
					</div>
					<div class="form-group">
						<label for="remark">扩展字段2</label> <input type="text"
							class="form-control" name="ext2" id="ext2">
					</div>
					<div class="form-group">
						<label for="YUL1">预留字段1</label> <input type="text"
							class="form-control" name="YUL1" id="YUL1">
					</div>
					<div class="form-group">
						<label for="YUL2">预留字段2</label> <input type="text"
							class="form-control" name="YUL2" id="YUL2">
					</div>
					<div class="form-group">
						<label for="YUL3">预留字段3</label> <input type="text"
							class="form-control" name="YUL3" id="YUL3">
					</div>
					<button type="submit" class="btn btn-primary">提交</button>
				</form>
			</div>
		</div>
	</div>

</body>
</html>