<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>支付页面</title>
<link rel="stylesheet"
	href="<?php echo HOST_STATIC;?>mobile/css/weui.min.css" />
<style type="text/css">
.button-sp-area {
	margin: 0 auto;
	padding: 15px 0;
	width: 60%
}
</style>
<script type="text/javascript"
	src="<?php echo HOST_STATIC;?>common/custom/jquery.min.js"></script>
</head>
<body>
	<div class="page">
		<div class="page__hd" style="text-align: center;">
			<h1 class="page__title">支付成功</h1>
		</div>
	</div>
</body>

</html>






