<?php include APPLICATION_PATH.'/application/views/index/layout/_header.phtml'; ?>
    <link href="<?php echo HOST_STATIC;?>common/css/login/login.css" rel="stylesheet">
	<div class="login-hd">
		<div class="left-bg"></div>
		<div class="right-bg"></div>
		<div class="hd-inner">
			<span class="logo"></span>
			<span class="split"></span>
			<span class="sys-name">商户管理系统</span>
		</div>
	</div>
	<div class="login-bd">
		<div class="bd-inner">
			<div class="inner-wrap">
				<div class="lg-zone">
					<div class="lg-box" style="top: 11px;">
						<div class="lg-label"><h4>管理员登录</h4></div>
						<div class="alert alert-error" id="layer" style="display: none">
			              <i class="iconfont">&#xe62e;</i>
			              <span id="msg_info">请输入用户名</span>
			            </div>
						<form>
							<div class="lg-username input-item clearfix">
								<i class="iconfont">&#xe6dd;</i>
								<input type="text" id="sp_number" onkeydown="hide()" onkeyup="this.value=this.value.replace(/[^0-9]/gi,'');" placeholder="商户号">
							</div>
							<div class="lg-username input-item clearfix">
								<i class="iconfont">&#xe60d;</i>
								<input type="text" id="login_name" onkeydown="hide()" onkeyup="this.value=this.value.replace(/[^0-9A-Za-z]/gi,'');" placeholder="账号">
							</div>
							<div class="lg-password input-item clearfix">
								<i class="iconfont">&#xe634;</i>
								<input type="password" id="password" onkeydown="hide()" placeholder="请输入密码">
							</div>
							<div class="lg-check clearfix">
								<div class="input-item">
									<i class="iconfont">&#xe633;</i>
									<input type="text" id="code_char" onkeydown="hide()" placeholder="验证码">
								</div>
								<img src="/index.php?m=Auth&c=login&a=code" onClick="click_code()" id="getcode_char" title="看不清点我一下~" align="absmiddle">
							</div>
							<div class="tips clearfix">
								 <label><input type="checkbox" id="remb_me" >记住用户名</label>
								<!--<a href="javascript:;" class="register">立即注册</a>
								<a href="javascript:;" class="forget-pwd">忘记密码？</a> -->
							</div>
							<div class="enter">
								<a href="javascript:;" class="purchaser enter-w284" onClick="login()">登陆</a>
							</div>
						</form>
					</div>
				</div>
				<div class="lg-poster"></div>
			</div>
		</div>
	</div>
	<div class="login-ft">
		<div class="ft-inner">
			<div class="about-us">
				<a href="javascript:;">关于我们</a>
				<a href="javascript:;">法律声明</a>
				<a href="javascript:;">服务条款</a>
				<a href="javascript:;">联系方式</a>
			</div>
			<div class="address">地址：北京市海淀区马连洼北路8号C座五层506-A031&nbsp;邮：100001&nbsp;&nbsp;Copyright&nbsp;©&nbsp;2018&nbsp;-&nbsp;2018&nbsp;北京扎呵呵科技有限公司&nbsp;版权所有</div>
			<div class="other-info">建议使用IE8及以上版本浏览器&nbsp;京ICP备18022684号-1&nbsp;E-mail：posteradmin@zhahehe.com</div>
		</div>
	</div>
<script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/login/login.js?v"></script>
<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>