<?php include APPLICATION_PATH.'/application/views/index/layout/_header.phtml'; ?>
	<div class="container" >

	 <div id="tb" class="easyui-panel"   style="background-color:#f1f1f1">
        <div class="conditions" style="margin:20px 20px 20px ;">
            <span class="con-span">商品编码 </span>
            <input class="easyui-textbox" type="text" name="self_code" id="self_code" style="margin-left:10px;width:166px;height:35px;line-height:35px;" />
            <span class="con-span">商品名称 </span>
            <input class="easyui-textbox" type="text" name="name" id="name" style="margin-left:10px;width:166px;height:35px;line-height:35px;" />

            <a href="javascript:;" class="easyui-linkbutton query" style="margin-left:10px;" iconCls="icon-search" data-options="selected:true">查询</a>
            <a href="javascript:;" class="easyui-linkbutton reset" style="margin-left:10px;" iconCls="icon-reload">重置</a>
            <a href="javascript:;" class="easyui-linkbutton more"  style="margin-left:10px;" iconCls="icon-more">更多</a>
        </div>
        <div class="conditions hide" style="margin:20px 20px 20px ">
            <span class="con-span">品牌名称 </span>
            <input class="easyui-combobox" name="info[brand_id]" id="brand_id"  style="width:166px;height:35px;line-height:35px;"
                   data-options="
										url:'/?c=Public&a=brand',
										method:'get',
										valueField:'id',
										textField:'name',
										multiple:true,
										panelHeight:'200'
									">

        	<span class="con-span">操作人 </span>
            <input class="easyui-textbox" type="text" name="admin_name" id="admin_name" style="margin-left:10px;width:166px;height:35px;line-height:35px;" />
        	
        	<span class="con-span">操作时间 </span>
        	<input class="easyui-datebox" style="width:166px;height:35px;line-height:35px;" name="start_time" id="start_time" />
        	<span class="con-span"> —— </span>
        	<input class="easyui-datebox" style="width:166px;height:35px;line-height:35px;" name="end_time" id="end_time" />
        </div>
     	<div class="conditions hide" style="margin:20px 20px 20px ">
            <span class="con-span">备注 </span>
            <input class="easyui-textbox" type="text" name="note" id="note" style="margin-left:10px;width:166px;height:35px;line-height:35px;"></input>
        </div>
  
      </div>
      <table id="dg"   class="easyui-datagrid" ></table>
 </div>

    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.list.js"></script>
    <script type="text/javascript" src="<?php echo HOST_STATIC; ?>common/js/common/qdd.grid.js"></script>
<script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/stock/list.js"></script> 

<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>