<?php include APPLICATION_PATH.'/application/views/index/layout/_header_v2.phtml'; ?>
<script type="text/javascript">
	document.domain  = 'zhahehe.com';
</script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>common/js/webuploader/0.1.5/webuploader.css">
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/webuploader/0.1.5/webuploader.js"></script> 
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/upload.js"></script> 
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/sprintf.js"></script> 
<script type="text/javascript" src="<?php echo HOST_STATIC;?>common/js/multiple_upload.js"></script> 
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>common/js/kindeditor/themes/default/default.css">
<script type="text/javascript" charset="utf-8" src="<?php echo HOST_STATIC;?>common/js/kindeditor/kindeditor-all-min.js"></script>
<link href="<?php echo HOST_STATIC;?>common/css/basic_info.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC;?>qdds/css/page/product/detail.css">
 <style>

</style>   
	<div style="margin:20px 0;"></div>
		<div style="padding:10px 60px 20px 60px">
	    <form >
	    	<div class="content">		
	    	<div class="easyui-tabs1" style="width:100%;">
		      <div title="查看商户" data-options="closable:false" class="basic-info">
		      	<div class="column"><span class="current">基本信息</span></div>
		      	<table class="kv-table">
					<tbody>
						<tr>
							<td class="kv-label">商品ID</td>
							<td class="kv-content"><?php echo $detail['id']?></td>
							<td class="kv-label">商品名称</td>
							<td class="kv-content"><?php echo $detail['name']?></td>
							<td class="kv-label">商品编号</td>
							<td class="kv-content"><?php echo $detail['self_code']?></td>
						</tr>
						<tr>
							<td class="kv-label">商品分类</td>
							<td class="kv-content"><?php echo $detail['category_name']?></td>
							<td class="kv-label">网点名称</td>
							<td class="kv-content"><?php echo $detail['multi_point']['0']['multi_point_name']?></td>
							<td class="kv-label">自定义码</td>
							<td class="kv-content"><?php echo $detail['custom_code']?></td>
						</tr>
						<tr>
							<td class="kv-label">商品品牌</td>
							<td class="kv-content"><?php echo $detail['brand_name']?></td>
							<td class="kv-label">是否含有鉴定证书</td>
							<td colspan="3" class="kv-content"><?php echo $detail['appraisal_status'] == '1'?'否':'是'?></td>
						</tr>
						<tr>
                            <td class="kv-label">公价</td>
                            <td class="kv-content"><?php echo $detail['market_price']?></td>
                            <td class="kv-label">销售价</td>
                            <td class="kv-content"><?php echo $detail['sale_price'];?></td>
                            <td class="kv-label">渠道价</td>
                            <td class="kv-content"><?php echo $detail['channel_price'];?></td>
                        </tr>
                        <tr>
                            <td class="kv-label">采购价</td>
                            <td class="kv-content" ><?php echo $detail['purchase_price']?></td>
                            <td class="kv-label">是否支持退换货</td>
                            <?php if ($detail['sale_is_up'] == \Product\ProductModel::IS_UP_2 || $detail['channel_is_up'] == \Product\ProductModel::IS_UP_2) { ?>
                                <td class="kv-content"><?php echo  $detail['is_return'] == '2'?'是':'否'; ?></td>
                                <td class="kv-label">黄金重量</td>
                                <td class="kv-content"><?php echo  $detail['weight']; ?>克</td>
                            <?php } else { ?>
                                <td class="kv-content" colspan="3"><?php echo  $detail['is_return'] == '2'?'是':'否'; ?></td>
                            <?php }?>
                        </tr>
                        <tr>
							<td class="kv-label">建档人</td>
							<td class="kv-content"><?php echo $detail['admin_name']?></td>
							<td class="kv-label">添加时间</td>
							<td class="kv-content"><?php echo $detail['created_at']?></td>							
							<td class="kv-label">当前库存</td>
							<td class="kv-content"><?php echo $detail['stock']?></td>
						</tr>
						<tr>
						</tr>	
					</tbody>
				</table>
	    	</div>
	    	</div></div>
	    	
	    	<table cellpadding="5" style="margin:20px 0;margin-bottom: 100px;">
	    		<tbody>
                    <tr>
                        <td> 备注</td>
                        <td width="800">
                            <textarea disabled name="info[note]" style="width:800px; height:80px;"><?php echo $detail['note'];?></textarea>
                        </td>
                    </tr>
		    		<tr >
		    			<td>商品主图</td>
		    			<td>
		    				<img id="logo_show_info" class="lazy" data-original="<?php echo HOST_FILE.$detail['logo_url'];?>" width="100" height="100"  />
		    			</td>
		    		</tr>
		    		<tr>
		    			<td>商品附图</td>
		    			<td>
		    				
		    					<?php
		    					 if (is_array($detail['imglist']) &&  count($detail['imglist']) > 0) {
									 foreach ($detail['imglist'] as $key => $value) {
		    					 ?>
		    						<img id="logo_show_info" width="100" height="100" class="lazy" data-original="<?php echo HOST_FILE.$value['img_url'];?>"  />
		    					<?php 
									 }
								 }
		    					
		    					?>
		    			</td>
		    		</tr>
		    		<tr> 
		    			<td>商品视频</td>
		    			<td>
		    				<div class="uploader-thum-container">
		    					<div id="videourl" <?php if (!$detail['video_url']) {?> style="display: none" <?php }?>>
									<video width="300" height="200" controls >
                                        <source src="<?php echo HOST_FILE.$detail['video_url'];?>" type="video/mp4">
                                    </video>
                                </div>
							</div>
		    			</td>
		    		</tr> 
		    		<?php if ($detail['attr'] != '1' && isset($detail['attribute']) && is_array($detail['attribute']) && count($detail['attribute']) > 0) { ?>
		    		<tr>
		    			<td><span class="red">*</span> 商品属性</td>
		    			<td>
		    				<table disabled="disabled" style="width:800px" id="erpAttributeList" class=" table table-border table-bordered table-bg table-hover table-sort ">
        					<tr>
        						<th width="50%">属性</th>
        						<th width="50%">属性明细</th>
        					</tr>
        					
        					<?php foreach ($detail['attribute'] as $key => $value): ?>
        						<tr class="attribute_class" data-id="<?php echo $value['attribute_id'];?>" id="values_<?php echo $value['attribute_id'];?>">
        							<th class="w9">
        								
        								<?php echo $value['attribute_name'];?>
        							</th>
        							<th>
        								<?php
        								 /*单选*/
        								 if($value['input_type'] == 1){?>
        								 	
        									<select  disabled="disabled" name="select[]"   style="width:300px;height:35px;line-height:35px;">
        									<?php foreach ($value['values'] as $k => $val): ?>
        										<option <?php if($val['selectd']){?> selected="selected" <?php }?>
        											value='<?php 
        										$select = [];
        										$select['attribute_id'] = $value['attribute_id'];
        										$select['attribute_name'] = $value['attribute_name'];
        										$select['attribute_value_id'] = $val['id'];
        										$select['attribute_value_name'] = $val['value'];
        										echo json_encode($select);?>' ><?php echo $val['value']?></option>
        									<?php endforeach ?>
        									</select>
        									
        								<?php }?>
        								<?php 
        									/*多选*/
        									if($value['input_type'] == 2){?>
        									<?php foreach ($value['values'] as $k => $val): ?>
        										
        											<input  disabled="disabled"
        											<?php if($val['selectd']){?> checked="checked" <?php }?> name="checkbox[]" 
        										value='<?php 
        										$checkbox = [];
        										$checkbox['attribute_id'] = $value['attribute_id'];
        										$checkbox['attribute_name'] = $value['attribute_name'];
        										$checkbox['attribute_value_id'] = $val['id'];
        										$checkbox['attribute_value_name'] = $val['value'];
        										echo json_encode($checkbox);?>' type="checkbox" id="checkbox-<?php echo $val['id']?>">
        											<label for="checkbox-<?php echo $val['id']?>"><?php echo $val['value']?>&nbsp;</label>
        										
        									<?php endforeach ?>
        								<?php }?>
        								
        								<?php if($value['input_type'] == 3){?>
        									<input type="text" disabled="disabled" class="easyui-textbox"  style="width:300px;height:35px;line-height:35px;"
        									 value="<?php echo $value['attribute_value_name'];?>" 
        									 name="input[<?php echo $value['attribute_id']?>]" class="input-text" placeholder="" />
        								<?php }?>
        							</th>
        						</tr>
        					<?php endforeach ?>
        				</table>
		    			</td>
		    		</tr>
		    		<?php } ?>
		    		<tr>
		    			<td><span class="red">*</span> 商品详情</td>
		    			<td width="800">
		    				<textarea  id="myEditor" name="info[introduction]" style="width:100%;height:240px;">
							    <?php echo $detail['introduction'];?><br/>
							    
							    <?php if ($detail['is_return'] == '1') {?>
							    <div style="margin-left: 45%">不退货声明</div>
                            <span>  绝当品是指质押在商行到期未赎的民用物品，一般包括各种有价的名表名包、珠宝玉 石、贵金属首饰、数码产品等。绝当品具有以下优势:
								<br/>
                                	1.正品保真，绝当品在上柜销售之前均经过专业鉴定师鉴定，确保为真品;
            					<br/>                    
                                	2.价格实惠，商的特性让绝当品在价格上具有很大优势，自古以来，商行都是淘宝的好去处。
                                	鉴于以上原因，商行销售的绝当品非质量问题不支持 7 天无理由退换货，所有商品在您点击确认收货或系统 14 天自动确认收货后即不支持退款退货，请您知悉。</span>
                                <?php }?>	
							</textarea>
		    			</td>
		    		</tr>
                    <tr>
                        <td> 渠道备注</td>
                        <td width="800">
		    				<textarea style="width:100%;height:200px;" disabled>
                                <?php echo $detail['channel_note'];?>
							</textarea>
                        </td>
                    </tr>
	    		</tbody>
	    	</table>
	    	<div style="padding:25px;position: fixed;bottom: 0px;width: 100%;background: #f1f1f1;text-align: center;margin-left: -70px;">
		    	<?php if ($_GET['origin'] == 'recovery') { ?>
                    <a href="/index.php?m=Recovery&c=Recovery&a=list" style="margin-left:15px" class="easyui-linkbutton" >返回</a>
                <?php } else { ?>
                    <a href="/index.php?m=Product&c=Product&a=list" style="margin-left:15px" class="easyui-linkbutton" >返回</a>
                <?php }?>
		    </div>
	    </form>
	    
	</div>
	
     <div style="display: none">   	
        <span class="con-span"></span>
    	<input class="easyui-datebox" type="hidden" id="start_time" />
    	<span class="con-span"></span>
    	<input class="easyui-datebox" type="hidden" id="end_time" />
    </div>           
        
   
<script type="text/javascript" src="<?php echo HOST_STATIC;?>qdds/js/page/product/onstatus.js"></script> 

<script type="text/javascript">
	

	$(function(){
		 
		  var qddUpload = Object.create(QddUpload);		
		  //上传地址			
	      qddUpload.urlUpload = '<?php echo HOST_FILE;?>/img.php?classify=product';
	      qddUpload.callBack = function(response) {
	      		$("#logo_show_info").attr("src",'<?php echo HOST_FILE;?>'+response.data);
	      }
	      qddUpload.run();
		  
		  var uploader = Object.create(QddMulitipleUpload);
		  uploader.urlUpload = '<?php echo HOST_FILE;?>/img.php?classify=product';//请求方式
		  uploader.filePicker =  'filePicker-3';	//焦点按钮id
		  uploader.filePicker2 =  'filePicker2';
		  uploader.accept =  {
		      title: 'Images',
		      extensions : 'gif,jpg,jpeg,bmp,png',
		      mimeTypes : '*/*'
		  };
		  uploader.run();
		  
		  $('#category_id').combotree('setValues', '<?php echo $detail['category_id'];?>'); 
		  
		  
		  KindEditor.ready(function(K) {
			K.create('#myEditor', {
                items:[
                    'source', '|', 'undo', 'redo', '|', 'preview', 'print', 'code', 'cut', 'copy', 'paste',
                    'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
                    'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
                    'superscript', 'clearhtml', 'quickformat', 'selectall', '|', 'fullscreen', '/',
                    'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
                    'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 'multiimage',
                    'flash', 'media', 'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
                    'anchor', 'link', 'unlink', '|', 'about'
                ],
				allowFileManager : true,
				uploadJson : '<?php echo HOST_FILE;?>/upload_json.php',  
       			fileManagerJson : '<?php echo HOST_FILE;?>/file_manager_json.php'
			});
		});
		 
	})
	
	
</script>	    


<?php include APPLICATION_PATH.'/application/views/index/layout/_footer.phtml'; ?>