<!-- 审核退货弹出窗 start -->
<style>
    .td-title {
        vertical-align: middle !important;
        text-align: right;
    }
</style>
<link rel="stylesheet" type="text/css" href="<?php echo HOST_STATIC; ?>common/css/table.css">
<div id="return-reject-dialog" class="easyui-dialog" title="拒收" style="width:640px;"
     data-options="iconCls:'icon-save',modal:true,collapsible:false,closed:true">

    <form action="/index.php?m=Marketing&c=SalesReturn&a=list" id="reject_form" method="post" autocomplete="off">
        <input type="hidden" name="format" value="reject">
        <input type="hidden" name="id" id="id" value="">
        <table class="table table table-bordered">
            <tr>
                <td class="td-title"></td>
                <td>
                    <label for="return_back">
                        <input type="radio" name="fd[platform_reject_type]" checked="checked" value="back" id="return_back"> 快递拒收
                    </label>

                    <label for="return_express">
                        <input type="radio" name="fd[platform_reject_type]" value="express" id="return_express"> 商品寄回
                    </label>
                </td>
            </tr>
            <tr class="return_back_option">
                <td class="td-title"><span class="red">*</span>姓名</td>
                <td>
                    <input class="easyui-validatebox" type="text" name="fd[platform_reject_content][name]"
                           id="platform_reject_content_name"
                           data-options="required:true"
                           style="width:300px;height:35px;line-height:35px;"/>
                </td>
            </tr>
            <tr class="return_back_option">
                <td class="td-title"><span class="red">*</span>手机</td>
                <td>
                    <input class="easyui-validatebox" type="text" name="fd[platform_reject_content][mobile]"
                           id="platform_reject_content_mobile"
                           data-options="required:true,validType:['phone']"
                           style="width:300px;height:35px;line-height:35px;"/>
                </td>
            </tr>

            <tr class="return_back_option">
                <td class="td-title"><span class="red">*</span>选择省市区</td>
                <td id="psa2"></td>
            </tr>

            <tr class="return_back_option">
                <td class="td-title"><span class="red">*</span>详细地址</td>
                <td>
                    <input class="easyui-validatebox" type="text" name="fd[platform_reject_content][address]"
                           data-options="required:true"
                           id="platform_reject_content_address"
                           style="width:300px;height:35px;line-height:35px;"/>
                </td>
            </tr>
            <tr>
                <td class="td-title"><span class="red">*</span>拒收原因</td>
                <td>
                    <input class="easyui-validatebox" data-options="required:true" type="text" name="fd[platform_reject_reason]"
                           style="width:300px;height:35px;line-height:35px;"/>
                </td>
            </tr>
            <tr class="return_express_option">
                <td class="td-title"><span class="red">*</span>物流公司</td>
                <td>
                    <select name="fd[platform_reject_content][express_id]" style="width:300px;height:35px;line-height:35px;">
                        <?php foreach ($data['expressCompany'] as $key => $val) { ?>
                            <option value="<?php echo $val['id'] ?>"><?php echo $val['name'] ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr class="return_express_option">
                <td class="td-title"><span class="red">*</span>物流单号</td>
                <td>
                    <input class="easyui-validatebox" name="fd[platform_reject_content][express_no]"
                           id="platform_reject_content_express_no"
                           data-options="required:true"
                           style="width:400px;height:35px;line-height:35px; " value="">
                </td>
            </tr>


        </table>

        <div style="padding:15px;text-align: center">
            <input type="submit" class="easyui-linkbutton" data-options="selected:true" value="确定">
            <a href="javascript:$('#return-reject-dialog').window('close');" style="margin-left:50px" class="easyui-linkbutton">取消</a>
        </div>
    </form>

</div>
<!-- 审核退货弹出窗 end -->
<script>
    $(function () {
        area_child(0, 1);

        $("#return-reject-dialog").find('input[name="fd[platform_reject_type]"]').on('click', function () {
            var val = $(this).val();
            var $backOptions = $(".return_back_option");
            var $expressOptions = $(".return_express_option");
            if (val === 'back') {
                $backOptions.find("input").attr('disabled', true);
                $backOptions.find("select").attr('disabled', true);
                $expressOptions.find("input").attr('disabled', true);
                $expressOptions.find("select").attr('disabled', true);
                $("#platform_reject_content_name").validatebox('disableValidation');
                $("#platform_reject_content_mobile").validatebox('disableValidation');
                $("#platform_reject_content_address").validatebox('disableValidation');
                $("#platform_reject_content_express_no").validatebox('disableValidation');
                $expressOptions.hide();
            } else {
                $backOptions.find("input").attr('disabled', false);
                $backOptions.find("select").attr('disabled', false);
                $expressOptions.find("input").attr('disabled', false);
                $expressOptions.find("select").attr('disabled', false);
                $("#platform_reject_content_name").validatebox('enableValidation');
                $("#platform_reject_content_mobile").validatebox('enableValidation');
                $("#platform_reject_content_address").validatebox('enableValidation');
                $("#platform_reject_content_express_no").validatebox('enableValidation');
                $expressOptions.show();
            }
        });

        /**
         * 提交表单
         */
        $('#reject_form').form({
            onSubmit: function () {
                var isValid = $(this).form('validate');
                if (!isValid) {
                    $.messager.progress('close');
                    return false;
                }
                $("input[type='submit']").attr('disabled', true);
                return true;
            },
            success: function (data) {
                try {
                    var data = JSON.parse(data);
                    if (data.code == '200') {
                        location.href = 'index.php?m=Marketing&c=SalesReturn&a=list';
                    } else {
                        throw data.msg;
                    }
                } catch (e) {
                    $.messager.alert('提示', e.msg);
                    $("input[type='submit']").attr('disabled', false);
                }
            }
        });
    });
</script>
